#base "../../^customizations/#enabled/medic_minichargemeter_hudmediccharge.res"
#base "../../^customizations/#enabled/medic_nochargemeter_hudmediccharge.res"
#base "../../^customizations/#enabled/medic_percentagenearcrosshair_hudmediccharge.res"
#base "../../^customizations/knedit/hudmediccharge.res"
#base "../../^customizations/^basefiles/hudmediccharge.res"